Use a larger (10 minute) timeout for rsync to exit after applying
balena-io/node-docker-delta pull request #28
Opened 2018-10-24 20:49 UTC by pcarranzav

This solves unnecessary timeouts when disk IO is very slow.

Change-type: patch
Signed-off-by: Pablo Carranza Velez <pablocarranza@gmail.com>

2018-10-24 20:52 UTC, dfunckt requested changes
I don't think this will have the intended effect -- it will just wait 10 miinutes before trying to kill rsync (via SIGUSR1) instead of a few seconds. Rsync will still exit with the same exit code in both cases. I do not know the underlying reason why this happens, hence the weird comment I had to leave behind.

2018-10-24 20:54 UTC, pcarranzav commented
@dfunckt I just found on a device that rsync can take more than 5 seconds and then exit *successfully*. I made this timeout bigger and deltas started succeeding. This explains the cases we've seen where the supervisor fell back to pulling from scratch.

2018-10-24 21:03 UTC, dfunckt approved these changes

2018-10-25 07:59 UTC, richbayliss approved these changes
Looks OK

2018-10-25 17:00 UTC, merged